/**
 * campaign.ts — Tallywise reels, BATCH 2 (75 reels).
 * Excludes the original 6 categories (cashflow, forecasting, estimating, jobcosting,
 * taxes, payroll) — those are batch 1 and already rendered.
 * Same Reel.tsx / Logo.tsx / CTA. Render these ids; do not rewrite the copy.
 */

import {ReelData} from './Reel';

const CTA = 'Free Cash Flow Dashboard';

export const CAMPAIGN: ReelData[] = [
  {
    id: "reel-subscriptions-1",
    title: "Zombie Subscriptions",
    cards: [
      {dur: 120, fontSize: 108, lines: [[{t: "You're paying for"}], [{t: "apps nobody"}], [{t: "has opened in months."}]]},
      {dur: 120, fontSize: 102, lines: [[{t: "Half your software"}], [{t: "is a ghost"}], [{t: "still "}, {t: "charging", g: true}, {t: " you."}]]},
      {dur: 114, fontSize: 100, lines: [[{t: "You forgot you"}], [{t: "even "}, {t: "signed up", g: true}], [{t: "for three of them."}]]},
      {dur: 108, fontSize: 112, allGreen: true, lines: [[{t: "We hunt down"}], [{t: "the dead apps"}], [{t: "and cancel them."}]]},
      {dur: 102, fontSize: 104, lines: [[{t: "Kill the zombie subscriptions."}]], cta: CTA},
    ],
  },
  {
    id: "reel-subscriptions-2",
    title: "The 2.5x Surprise",
    cards: [
      {dur: 120, fontSize: 108, lines: [[{t: "Guess your monthly"}], [{t: "software bill."}], [{t: "Now double it."}]]},
      {dur: 120, fontSize: 102, lines: [[{t: "What you think"}], [{t: "you spend on apps"}], [{t: "is "}, {t: "half", g: true}, {t: " the truth."}]]},
      {dur: 114, fontSize: 100, lines: [[{t: "The auto-renewals"}], [{t: "hide on "}, {t: "three", g: true}], [{t: "different cards."}]]},
      {dur: 108, fontSize: 112, allGreen: true, lines: [[{t: "We total up"}], [{t: "every subscription"}], [{t: "in one place."}]]},
      {dur: 102, fontSize: 104, lines: [[{t: "See your real software bill."}]], cta: CTA},
    ],
  },
  {
    id: "reel-subscriptions-3",
    title: "Free Trial, Paid Forever",
    cards: [
      {dur: 120, fontSize: 108, lines: [[{t: "That \"free trial\""}], [{t: "from last spring?"}], [{t: "Still billing you."}]]},
      {dur: 120, fontSize: 102, lines: [[{t: "Free trials don't"}], [{t: "expire \u2014 they "}, {t: "convert", g: true}], [{t: "quietly."}]]},
      {dur: 114, fontSize: 100, lines: [[{t: "You've paid a year"}], [{t: "for a tool you"}], [{t: "used "}, {t: "once", g: true}]]},
      {dur: 108, fontSize: 112, allGreen: true, lines: [[{t: "We catch the trials"}], [{t: "before they"}], [{t: "become forever."}]]},
      {dur: 102, fontSize: 104, lines: [[{t: "Stop paying for free."}]], cta: CTA},
    ],
  },
  {
    id: "reel-subscriptions-4",
    title: "Seats for Ghosts",
    cards: [
      {dur: 120, fontSize: 108, lines: [[{t: "You're paying"}], [{t: "per user. For users"}], [{t: "who quit."}]]},
      {dur: 120, fontSize: 102, lines: [[{t: "Empty seats cost"}], [{t: "the same as"}], [{t: "full ones", g: true}]]},
      {dur: 114, fontSize: 100, lines: [[{t: "You're still paying"}], [{t: "for "}, {t: "logins", g: true}], [{t: "that left in 2023."}]]},
      {dur: 108, fontSize: 112, allGreen: true, lines: [[{t: "We right-size"}], [{t: "every license"}], [{t: "to who's actually here."}]]},
      {dur: 102, fontSize: 104, lines: [[{t: "Pay for real seats only."}]], cta: CTA},
    ],
  },
  {
    id: "reel-subscriptions-5",
    title: "Shadow IT",
    cards: [
      {dur: 120, fontSize: 108, lines: [[{t: "Your team signs up"}], [{t: "for tools"}], [{t: "you've never heard of."}]]},
      {dur: 120, fontSize: 102, lines: [[{t: "\"Shadow IT\" is"}], [{t: "spending you"}], [{t: "can't even see", g: true}]]},
      {dur: 114, fontSize: 100, lines: [[{t: "Nobody owns"}], [{t: "the software budget."}], [{t: "So nobody "}, {t: "watches", g: true}, {t: " it."}]]},
      {dur: 108, fontSize: 112, allGreen: true, lines: [[{t: "We put every"}], [{t: "tool on one"}], [{t: "accountable list."}]]},
      {dur: 102, fontSize: 104, lines: [[{t: "Take back your software spend."}]], cta: CTA},
    ],
  },
  {
    id: "reel-cardfees-1",
    title: "The 3% Skim",
    cards: [
      {dur: 120, fontSize: 108, lines: [[{t: "Every sale you make,"}], [{t: "someone takes"}], [{t: "a cut first."}]]},
      {dur: 120, fontSize: 102, lines: [[{t: "Card fees skim"}], [{t: "3%", g: true}, {t: " off"}], [{t: "the top. Silently."}]]},
      {dur: 114, fontSize: 100, lines: [[{t: "You've never once"}], [{t: "read your "}, {t: "processor", g: true}], [{t: "statement."}]]},
      {dur: 108, fontSize: 112, allGreen: true, lines: [[{t: "We audit the fees"}], [{t: "and claw"}], [{t: "them back."}]]},
      {dur: 102, fontSize: 104, lines: [[{t: "Cut your card fees."}]], cta: CTA},
    ],
  },
  {
    id: "reel-cardfees-2",
    title: "Flat-Rate Trap",
    cards: [
      {dur: 120, fontSize: 108, lines: [[{t: "\"Simple flat rate!\""}], [{t: "they said."}], [{t: "It's not simple."}]]},
      {dur: 120, fontSize: 102, lines: [[{t: "Flat pricing hides"}], [{t: "the "}, {t: "markup", g: true}], [{t: "you're actually paying."}]]},
      {dur: 114, fontSize: 100, lines: [[{t: "You picked the plan"}], [{t: "for "}, {t: "easy", g: true}], [{t: "not for cheap."}]]},
      {dur: 108, fontSize: 112, allGreen: true, lines: [[{t: "We move you to"}], [{t: "transparent"}], [{t: "interchange-plus."}]]},
      {dur: 102, fontSize: 104, lines: [[{t: "Stop overpaying to get paid."}]], cta: CTA},
    ],
  },
  {
    id: "reel-cardfees-3",
    title: "PCI Penalty",
    cards: [
      {dur: 120, fontSize: 108, lines: [[{t: "There's a fee"}], [{t: "on your statement"}], [{t: "you can't explain."}]]},
      {dur: 120, fontSize: 102, lines: [[{t: "It's a "}, {t: "PCI", g: true}], [{t: "non-compliance"}], [{t: "penalty. Monthly."}]]},
      {dur: 114, fontSize: 100, lines: [[{t: "You're being fined"}], [{t: "for a form"}], [{t: "you never "}, {t: "filled out", g: true}]]},
      {dur: 108, fontSize: 112, allGreen: true, lines: [[{t: "We kill the"}], [{t: "junk fees"}], [{t: "hiding in the fine print."}]]},
      {dur: 102, fontSize: 104, lines: [[{t: "Find the hidden fees."}]], cta: CTA},
    ],
  },
  {
    id: "reel-cardfees-4",
    title: "Premium Card, Premium Fee",
    cards: [
      {dur: 120, fontSize: 108, lines: [[{t: "Customer pays with"}], [{t: "a fancy rewards card."}], [{t: "You pay for it."}]]},
      {dur: 120, fontSize: 102, lines: [[{t: "Their points"}], [{t: "come out of"}], [{t: "your margin", g: true}]]},
      {dur: 114, fontSize: 100, lines: [[{t: "You eat a higher fee"}], [{t: "every time"}], [{t: "and never "}, {t: "notice", g: true}]]},
      {dur: 108, fontSize: 112, allGreen: true, lines: [[{t: "We show which"}], [{t: "payments actually"}], [{t: "cost you."}]]},
      {dur: 102, fontSize: 104, lines: [[{t: "Know your true cost to get paid."}]], cta: CTA},
    ],
  },
  {
    id: "reel-cardfees-5",
    title: "Death by Basis Points",
    cards: [
      {dur: 120, fontSize: 108, lines: [[{t: "A few tenths"}], [{t: "of a percent."}], [{t: "Who cares, right?"}]]},
      {dur: 120, fontSize: 102, lines: [[{t: "On "}, {t: "every", g: true}, {t: " sale,"}], [{t: "all year \u2014"}], [{t: "that's real money."}]]},
      {dur: 114, fontSize: 100, lines: [[{t: "You've never"}], [{t: "done the "}, {t: "math", g: true}], [{t: "on what fees cost."}]]},
      {dur: 108, fontSize: 112, allGreen: true, lines: [[{t: "We do the math"}], [{t: "and shrink"}], [{t: "the skim."}]]},
      {dur: 102, fontSize: 104, lines: [[{t: "Run the fee math."}]], cta: CTA},
    ],
  },
  {
    id: "reel-classification-1",
    title: "1099 Roulette",
    cards: [
      {dur: 120, fontSize: 108, lines: [[{t: "You call them"}], [{t: "a contractor."}], [{t: "The IRS might not."}]]},
      {dur: 120, fontSize: 102, lines: [[{t: "One wrong "}, {t: "1099", g: true}], [{t: "is back taxes"}], [{t: "with interest."}]]},
      {dur: 114, fontSize: 100, lines: [[{t: "Nobody ever"}], [{t: "checked if it's"}], [{t: "actually "}, {t: "legal", g: true}]]},
      {dur: 108, fontSize: 112, allGreen: true, lines: [[{t: "We classify your"}], [{t: "people the way"}], [{t: "the IRS would."}]]},
      {dur: 102, fontSize: 104, lines: [[{t: "Get your workers classified right."}]], cta: CTA},
    ],
  },
  {
    id: "reel-classification-2",
    title: "The Audit Trigger",
    cards: [
      {dur: 120, fontSize: 108, lines: [[{t: "Treating W-2 work"}], [{t: "like 1099"}], [{t: "to save a buck?"}]]},
      {dur: 120, fontSize: 102, lines: [[{t: "That \"savings\" is"}], [{t: "an "}, {t: "audit", g: true}], [{t: "with your name on it."}]]},
      {dur: 114, fontSize: 100, lines: [[{t: "You picked 1099"}], [{t: "because it was"}], [{t: "cheaper", g: true}, {t: ". Not legal."}]]},
      {dur: 108, fontSize: 112, allGreen: true, lines: [[{t: "We fix it before"}], [{t: "the DOL"}], [{t: "comes knocking."}]]},
      {dur: 102, fontSize: 104, lines: [[{t: "Lower your audit risk."}]], cta: CTA},
    ],
  },
  {
    id: "reel-classification-3",
    title: "Penalty Stack",
    cards: [
      {dur: 120, fontSize: 108, lines: [[{t: "Misclassify one worker."}], [{t: "Now stack"}], [{t: "the penalties."}]]},
      {dur: 120, fontSize: 102, lines: [[{t: "Back FICA, withholding,"}], [{t: "interest \u2014 it "}, {t: "compounds", g: true}], [{t: "fast."}]]},
      {dur: 114, fontSize: 100, lines: [[{t: "You have no idea"}], [{t: "what one"}], [{t: "mistake would "}, {t: "cost", g: true}]]},
      {dur: 108, fontSize: 112, allGreen: true, lines: [[{t: "We size the risk"}], [{t: "before it"}], [{t: "becomes a bill."}]]},
      {dur: 102, fontSize: 104, lines: [[{t: "See your exposure."}]], cta: CTA},
    ],
  },
  {
    id: "reel-classification-4",
    title: "Control Test",
    cards: [
      {dur: 120, fontSize: 108, lines: [[{t: "You set their hours."}], [{t: "Their tools."}], [{t: "Their process."}]]},
      {dur: 120, fontSize: 102, lines: [[{t: "If you control it,"}], [{t: "they're likely"}], [{t: "an "}, {t: "employee", g: true}]]},
      {dur: 114, fontSize: 100, lines: [[{t: "You've been calling"}], [{t: "an employee"}], [{t: "a \""}, {t: "contractor", g: true}, {t: ".\""}]]},
      {dur: 108, fontSize: 112, allGreen: true, lines: [[{t: "We run the"}], [{t: "three-factor test"}], [{t: "for real."}]]},
      {dur: 102, fontSize: 104, lines: [[{t: "Pass the control test."}]], cta: CTA},
    ],
  },
  {
    id: "reel-classification-5",
    title: "Clean It Up",
    cards: [
      {dur: 120, fontSize: 108, lines: [[{t: "You already"}], [{t: "misclassified."}], [{t: "Now what?"}]]},
      {dur: 120, fontSize: 102, lines: [[{t: "There's a "}, {t: "legal", g: true}], [{t: "way to fix it \u2014"}], [{t: "before they find it."}]]},
      {dur: 114, fontSize: 100, lines: [[{t: "Ignoring it"}], [{t: "doesn't make it"}], [{t: "go away", g: true}]]},
      {dur: 108, fontSize: 112, allGreen: true, lines: [[{t: "We file the fix"}], [{t: "and cap"}], [{t: "the damage."}]]},
      {dur: 102, fontSize: 104, lines: [[{t: "Fix it the right way."}]], cta: CTA},
    ],
  },
  {
    id: "reel-turnover-1",
    title: "150% Goodbye",
    cards: [
      {dur: 120, fontSize: 108, lines: [[{t: "A good employee quit."}], [{t: "That just cost you"}], [{t: "more than you think."}]]},
      {dur: 120, fontSize: 102, lines: [[{t: "Replacing them runs"}], [{t: "150%", g: true}], [{t: "of their salary."}]]},
      {dur: 114, fontSize: 100, lines: [[{t: "You budgeted their wage."}], [{t: "Not the "}, {t: "hole", g: true}], [{t: "they leave."}]]},
      {dur: 108, fontSize: 112, allGreen: true, lines: [[{t: "We price turnover"}], [{t: "so you"}], [{t: "stop bleeding on it."}]]},
      {dur: 102, fontSize: 104, lines: [[{t: "Cut the cost of quitting."}]], cta: CTA},
    ],
  },
  {
    id: "reel-turnover-2",
    title: "The 40% Nobody Counts",
    cards: [
      {dur: 120, fontSize: 108, lines: [[{t: "You think you pay"}], [{t: "them their"}], [{t: "hourly rate."}]]},
      {dur: 120, fontSize: 102, lines: [[{t: "Add taxes and benefits \u2014"}], [{t: "it's "}, {t: "40%", g: true}], [{t: "more."}]]},
      {dur: 114, fontSize: 100, lines: [[{t: "Your labor math"}], [{t: "forgot"}], [{t: "everything but", g: true}, {t: " the wage."}]]},
      {dur: 108, fontSize: 112, allGreen: true, lines: [[{t: "We show the"}], [{t: "true cost"}], [{t: "of every hire."}]]},
      {dur: 102, fontSize: 104, lines: [[{t: "See what labor really costs."}]], cta: CTA},
    ],
  },
  {
    id: "reel-turnover-3",
    title: "Can You Afford Them",
    cards: [
      {dur: 120, fontSize: 108, lines: [[{t: "You want to hire."}], [{t: "Can the business"}], [{t: "actually carry it?"}]]},
      {dur: 120, fontSize: 102, lines: [[{t: "A hire is a "}, {t: "fixed", g: true}], [{t: "cost that doesn't"}], [{t: "care about slow months."}]]},
      {dur: 114, fontSize: 100, lines: [[{t: "You've hired on a"}], [{t: "good month and"}], [{t: "regretted", g: true}, {t: " it in a slow one."}]]},
      {dur: 108, fontSize: 112, allGreen: true, lines: [[{t: "We stress-test"}], [{t: "the hire"}], [{t: "before you make it."}]]},
      {dur: 102, fontSize: 104, lines: [[{t: "Hire with the numbers."}]], cta: CTA},
    ],
  },
  {
    id: "reel-turnover-4",
    title: "Overtime Leak",
    cards: [
      {dur: 120, fontSize: 108, lines: [[{t: "Overtime crept in."}], [{t: "Nobody"}], [{t: "decided to spend it."}]]},
      {dur: 120, fontSize: 102, lines: [[{t: "Unplanned OT is"}], [{t: "payroll you"}], [{t: "never "}, {t: "approved", g: true}]]},
      {dur: 114, fontSize: 100, lines: [[{t: "You find out about"}], [{t: "the OT on the"}], [{t: "check", g: true}, {t: ", not before."}]]},
      {dur: 108, fontSize: 112, allGreen: true, lines: [[{t: "We flag the OT"}], [{t: "before it"}], [{t: "hits the run."}]]},
      {dur: 102, fontSize: 104, lines: [[{t: "Get ahead of overtime."}]], cta: CTA},
    ],
  },
  {
    id: "reel-turnover-5",
    title: "Ghost on Payroll",
    cards: [
      {dur: 120, fontSize: 108, lines: [[{t: "When's the last time"}], [{t: "you actually"}], [{t: "checked the payroll list?"}]]},
      {dur: 120, fontSize: 102, lines: [[{t: "You could be paying"}], [{t: "for a role"}], [{t: "that "}, {t: "quietly left", g: true}]]},
      {dur: 114, fontSize: 100, lines: [[{t: "Payroll runs itself \u2014"}], [{t: "which means"}], [{t: "nobody "}, {t: "watches", g: true}, {t: " it."}]]},
      {dur: 108, fontSize: 112, allGreen: true, lines: [[{t: "We reconcile who's"}], [{t: "paid against"}], [{t: "who's here."}]]},
      {dur: 102, fontSize: 104, lines: [[{t: "Audit your payroll."}]], cta: CTA},
    ],
  },
  {
    id: "reel-marketing-1",
    title: "Set and Forgotten",
    cards: [
      {dur: 120, fontSize: 108, lines: [[{t: "You launched an ad."}], [{t: "Then never"}], [{t: "looked again."}]]},
      {dur: 120, fontSize: 102, lines: [[{t: "\"Set and forget\""}], [{t: "is how "}, {t: "60%", g: true}], [{t: "of budgets vanish."}]]},
      {dur: 114, fontSize: 100, lines: [[{t: "You don't actually"}], [{t: "know which ad"}], [{t: "worked", g: true}]]},
      {dur: 108, fontSize: 112, allGreen: true, lines: [[{t: "We track the spend"}], [{t: "to the"}], [{t: "dollar it made."}]]},
      {dur: 102, fontSize: 104, lines: [[{t: "Stop burning ad budget."}]], cta: CTA},
    ],
  },
  {
    id: "reel-marketing-2",
    title: "No Tracking, No Clue",
    cards: [
      {dur: 120, fontSize: 108, lines: [[{t: "You spend on ads."}], [{t: "Do they"}], [{t: "make you money?"}]]},
      {dur: 120, fontSize: 102, lines: [[{t: "Without tracking,"}], [{t: "that's a "}, {t: "donation", g: true}], [{t: "not marketing."}]]},
      {dur: 114, fontSize: 100, lines: [[{t: "Half your campaigns"}], [{t: "have no"}], [{t: "conversion", g: true}, {t: " tracking."}]]},
      {dur: 108, fontSize: 112, allGreen: true, lines: [[{t: "We wire up tracking"}], [{t: "so spend"}], [{t: "has to prove itself."}]]},
      {dur: 102, fontSize: 104, lines: [[{t: "Make your ads accountable."}]], cta: CTA},
    ],
  },
  {
    id: "reel-marketing-3",
    title: "The Invisible Business",
    cards: [
      {dur: 120, fontSize: 108, lines: [[{t: "You spend"}], [{t: "under a grand"}], [{t: "a year on marketing."}]]},
      {dur: 120, fontSize: 102, lines: [[{t: "That's "}, {t: "95%", g: true}, {t: " below"}], [{t: "what a business"}], [{t: "your size should."}]]},
      {dur: 114, fontSize: 100, lines: [[{t: "You cut marketing"}], [{t: "first \u2014 then"}], [{t: "wonder why it's "}, {t: "quiet", g: true}]]},
      {dur: 108, fontSize: 112, allGreen: true, lines: [[{t: "We set a budget"}], [{t: "that actually"}], [{t: "gets you seen."}]]},
      {dur: 102, fontSize: 104, lines: [[{t: "Get a real marketing budget."}]], cta: CTA},
    ],
  },
  {
    id: "reel-marketing-4",
    title: "Last-Click Lie",
    cards: [
      {dur: 120, fontSize: 108, lines: [[{t: "You credit the ad"}], [{t: "that closed it."}], [{t: "Ignore the rest."}]]},
      {dur: 120, fontSize: 102, lines: [[{t: "The \"last click\""}], [{t: "gets the credit"}], [{t: "it didn't "}, {t: "earn", g: true}]]},
      {dur: 114, fontSize: 100, lines: [[{t: "You've killed the thing"}], [{t: "that "}, {t: "started", g: true}], [{t: "the sale."}]]},
      {dur: 108, fontSize: 112, allGreen: true, lines: [[{t: "We follow the whole"}], [{t: "path, not"}], [{t: "just the finish line."}]]},
      {dur: 102, fontSize: 104, lines: [[{t: "Fix your attribution."}]], cta: CTA},
    ],
  },
  {
    id: "reel-marketing-5",
    title: "ROI on What",
    cards: [
      {dur: 120, fontSize: 108, lines: [[{t: "\"How\u2019s marketing"}], [{t: "going?\""}], [{t: "\"Uh... good?\""}]]},
      {dur: 120, fontSize: 102, lines: [[{t: "If you can't name"}], [{t: "the "}, {t: "return", g: true}], [{t: "it's a guess."}]]},
      {dur: 114, fontSize: 100, lines: [[{t: "You've never tied"}], [{t: "a single sale"}], [{t: "back to a "}, {t: "channel", g: true}]]},
      {dur: 108, fontSize: 112, allGreen: true, lines: [[{t: "We put a number"}], [{t: "on every"}], [{t: "marketing dollar."}]]},
      {dur: 102, fontSize: 104, lines: [[{t: "Measure your marketing."}]], cta: CTA},
    ],
  },
  {
    id: "reel-ownerpay-1",
    title: "Last One Paid",
    cards: [
      {dur: 120, fontSize: 108, lines: [[{t: "Everyone gets paid."}], [{t: "Vendors, staff,"}], [{t: "the tax man."}]]},
      {dur: 120, fontSize: 102, lines: [[{t: "You're the "}, {t: "last", g: true}], [{t: "one in line."}], [{t: "Every time."}]]},
      {dur: 114, fontSize: 100, lines: [[{t: "Some months you"}], [{t: "skip "}, {t: "your own", g: true}], [{t: "paycheck. Quietly."}]]},
      {dur: 108, fontSize: 112, allGreen: true, lines: [[{t: "We pay you first,"}], [{t: "on purpose,"}], [{t: "like a real salary."}]]},
      {dur: 102, fontSize: 104, lines: [[{t: "Start paying yourself."}]], cta: CTA},
    ],
  },
  {
    id: "reel-ownerpay-2",
    title: "Owner's Draw Chaos",
    cards: [
      {dur: 120, fontSize: 108, lines: [[{t: "You pay yourself"}], [{t: "whenever the"}], [{t: "account looks okay."}]]},
      {dur: 120, fontSize: 102, lines: [[{t: "Random draws are"}], [{t: "how you "}, {t: "starve", g: true}], [{t: "the business."}]]},
      {dur: 114, fontSize: 100, lines: [[{t: "You have no idea"}], [{t: "what you"}], [{t: "actually "}, {t: "took", g: true}, {t: " last year."}]]},
      {dur: 108, fontSize: 112, allGreen: true, lines: [[{t: "We set a real"}], [{t: "owner's pay"}], [{t: "the business can carry."}]]},
      {dur: 102, fontSize: 104, lines: [[{t: "Put your pay on a system."}]], cta: CTA},
    ],
  },
  {
    id: "reel-ownerpay-3",
    title: "Rich Business, Broke You",
    cards: [
      {dur: 120, fontSize: 108, lines: [[{t: "The business is growing."}], [{t: "You're"}], [{t: "still broke."}]]},
      {dur: 120, fontSize: 102, lines: [[{t: "Reinvesting everything"}], [{t: "means paying"}], [{t: "yourself", g: true}, {t: " nothing."}]]},
      {dur: 114, fontSize: 100, lines: [[{t: "You've told yourself"}], [{t: "\""}, {t: "next year", g: true}, {t: "\""}], [{t: "for three years."}]]},
      {dur: 108, fontSize: 112, allGreen: true, lines: [[{t: "We build in"}], [{t: "owner pay"}], [{t: "that grows with you."}]]},
      {dur: 102, fontSize: 104, lines: [[{t: "Pay yourself like it's a job."}]], cta: CTA},
    ],
  },
  {
    id: "reel-ownerpay-4",
    title: "Personal Card Bailout",
    cards: [
      {dur: 120, fontSize: 108, lines: [[{t: "The business is short."}], [{t: "So you"}], [{t: "covered it. Again."}]]},
      {dur: 120, fontSize: 102, lines: [[{t: "Your personal card"}], [{t: "is not a"}], [{t: "credit line", g: true}]]},
      {dur: 114, fontSize: 100, lines: [[{t: "You've floated the"}], [{t: "business on"}], [{t: "your "}, {t: "own", g: true}, {t: " money."}]]},
      {dur: 108, fontSize: 112, allGreen: true, lines: [[{t: "We stop the"}], [{t: "personal bailouts"}], [{t: "for good."}]]},
      {dur: 102, fontSize: 104, lines: [[{t: "Stop funding it yourself."}]], cta: CTA},
    ],
  },
  {
    id: "reel-ownerpay-5",
    title: "What's It Even Worth",
    cards: [
      {dur: 120, fontSize: 108, lines: [[{t: "You built this."}], [{t: "What's it"}], [{t: "actually worth?"}]]},
      {dur: 120, fontSize: 102, lines: [[{t: "A business that"}], [{t: "can't pay its owner"}], [{t: "isn't an "}, {t: "asset", g: true}]]},
      {dur: 114, fontSize: 100, lines: [[{t: "You couldn't sell it"}], [{t: "because it's"}], [{t: "really just "}, {t: "your", g: true}, {t: " job."}]]},
      {dur: 108, fontSize: 112, allGreen: true, lines: [[{t: "We build it into"}], [{t: "something that"}], [{t: "pays you to own it."}]]},
      {dur: 102, fontSize: 104, lines: [[{t: "Build an asset, not a job."}]], cta: CTA},
    ],
  },
  {
    id: "reel-trades-1",
    title: "Bid at a Red Light",
    cards: [
      {dur: 120, fontSize: 108, lines: [[{t: "You priced the"}], [{t: "whole job at"}], [{t: "a red light."}]]},
      {dur: 120, fontSize: 102, lines: [[{t: "That's not a bid."}], [{t: "That's "}, {t: "gambling", g: true}], [{t: "with a clipboard."}]]},
      {dur: 114, fontSize: 100, lines: [[{t: "You found the loss"}], [{t: "on the final invoice,"}], [{t: "three weeks", g: true}, {t: " late."}]]},
      {dur: 108, fontSize: 112, allGreen: true, lines: [[{t: "We cost the job"}], [{t: "at hour two,"}], [{t: "not at year-end."}]]},
      {dur: 102, fontSize: 104, lines: [[{t: "Stop bidding blind."}]], cta: CTA},
    ],
  },
  {
    id: "reel-trades-2",
    title: "Change-Order Amnesia",
    cards: [
      {dur: 120, fontSize: 108, lines: [[{t: "\"Can you just"}], [{t: "add this?\""}], [{t: "Sure. For free, apparently."}]]},
      {dur: 120, fontSize: 102, lines: [[{t: "Every unlogged change"}], [{t: "is "}, {t: "free", g: true}, {t: " work"}], [{t: "with a smile."}]]},
      {dur: 114, fontSize: 100, lines: [[{t: "You've built stuff"}], [{t: "that was never"}], [{t: "in the "}, {t: "contract", g: true}]]},
      {dur: 108, fontSize: 112, allGreen: true, lines: [[{t: "We catch the changes"}], [{t: "so they"}], [{t: "hit the invoice."}]]},
      {dur: 102, fontSize: 104, lines: [[{t: "Bill every change order."}]], cta: CTA},
    ],
  },
  {
    id: "reel-trades-3",
    title: "Retainage Rot",
    cards: [
      {dur: 120, fontSize: 108, lines: [[{t: "10% of every job"}], [{t: "held back."}], [{t: "For months."}]]},
      {dur: 120, fontSize: 102, lines: [[{t: "Retainage is your"}], [{t: "money", g: true}], [{t: "someone else is holding."}]]},
      {dur: 114, fontSize: 100, lines: [[{t: "You've forgotten"}], [{t: "retainage you"}], [{t: "never "}, {t: "collected", g: true}]]},
      {dur: 108, fontSize: 112, allGreen: true, lines: [[{t: "We track every"}], [{t: "dollar held"}], [{t: "until it's yours."}]]},
      {dur: 102, fontSize: 104, lines: [[{t: "Collect your retainage."}]], cta: CTA},
    ],
  },
  {
    id: "reel-trades-4",
    title: "Material Markup Miss",
    cards: [
      {dur: 120, fontSize: 108, lines: [[{t: "Lumber went up."}], [{t: "Your bid"}], [{t: "didn't."}]]},
      {dur: 120, fontSize: 102, lines: [[{t: "You're eating the"}], [{t: "price hike", g: true}], [{t: "on every board."}]]},
      {dur: 114, fontSize: 100, lines: [[{t: "You quoted with"}], [{t: "last month's", g: true}], [{t: "material prices."}]]},
      {dur: 108, fontSize: 112, allGreen: true, lines: [[{t: "We keep your costs"}], [{t: "current so"}], [{t: "your bids are too."}]]},
      {dur: 102, fontSize: 104, lines: [[{t: "Bid on today's prices."}]], cta: CTA},
    ],
  },
  {
    id: "reel-trades-5",
    title: "Which Crew Pays",
    cards: [
      {dur: 120, fontSize: 108, lines: [[{t: "All your crews"}], [{t: "are busy. Are they"}], [{t: "all profitable?"}]]},
      {dur: 120, fontSize: 102, lines: [[{t: "Busy trucks and"}], [{t: "profitable", g: true}, {t: " trucks"}], [{t: "aren't the same."}]]},
      {dur: 114, fontSize: 100, lines: [[{t: "Your biggest job"}], [{t: "might be your"}], [{t: "worst", g: true}, {t: " margin."}]]},
      {dur: 108, fontSize: 112, allGreen: true, lines: [[{t: "We show profit"}], [{t: "by job"}], [{t: "and by crew."}]]},
      {dur: 102, fontSize: 104, lines: [[{t: "Find your money jobs."}]], cta: CTA},
    ],
  },
  {
    id: "reel-restaurant-1",
    title: "Food-Cost Creep",
    cards: [
      {dur: 120, fontSize: 108, lines: [[{t: "Your menu prices"}], [{t: "are the same."}], [{t: "Your costs aren't."}]]},
      {dur: 120, fontSize: 102, lines: [[{t: "Food cost crept"}], [{t: "to "}, {t: "40%", g: true}], [{t: "while you weren't looking."}]]},
      {dur: 114, fontSize: 100, lines: [[{t: "You haven't re-priced"}], [{t: "that entr\u00e9e since"}], [{t: "it "}, {t: "hurt", g: true}]]},
      {dur: 108, fontSize: 112, allGreen: true, lines: [[{t: "We watch food cost"}], [{t: "plate by"}], [{t: "plate."}]]},
      {dur: 102, fontSize: 104, lines: [[{t: "Protect your plate margin."}]], cta: CTA},
    ],
  },
  {
    id: "reel-restaurant-2",
    title: "Slow-Tuesday Labor",
    cards: [
      {dur: 120, fontSize: 108, lines: [[{t: "Same crew Tuesday"}], [{t: "as Friday."}], [{t: "Empty dining room."}]]},
      {dur: 120, fontSize: 102, lines: [[{t: "Overstaffed slow shifts"}], [{t: "quietly "}, {t: "eat", g: true}], [{t: "the whole week."}]]},
      {dur: 114, fontSize: 100, lines: [[{t: "You schedule by"}], [{t: "habit", g: true}], [{t: "not by covers."}]]},
      {dur: 108, fontSize: 112, allGreen: true, lines: [[{t: "We match labor"}], [{t: "to the covers"}], [{t: "you'll actually get."}]]},
      {dur: 102, fontSize: 104, lines: [[{t: "Right-size your labor."}]], cta: CTA},
    ],
  },
  {
    id: "reel-restaurant-3",
    title: "Comp and Waste",
    cards: [
      {dur: 120, fontSize: 108, lines: [[{t: "A comp here."}], [{t: "A remake there."}], [{t: "Some spoilage."}]]},
      {dur: 120, fontSize: 102, lines: [[{t: "\"It’s just one plate\""}], [{t: "times "}, {t: "a week", g: true}], [{t: "is real money."}]]},
      {dur: 114, fontSize: 100, lines: [[{t: "You've never counted"}], [{t: "what walks out"}], [{t: "the "}, {t: "back door", g: true}]]},
      {dur: 108, fontSize: 112, allGreen: true, lines: [[{t: "We put a number"}], [{t: "on comps,"}], [{t: "waste, and theft."}]]},
      {dur: 102, fontSize: 104, lines: [[{t: "Plug the kitchen leaks."}]], cta: CTA},
    ],
  },
  {
    id: "reel-restaurant-4",
    title: "Thin-Margin Panic",
    cards: [
      {dur: 120, fontSize: 108, lines: [[{t: "Packed house."}], [{t: "Great night."}], [{t: "Where's the money?"}]]},
      {dur: 120, fontSize: 102, lines: [[{t: "Restaurants live on"}], [{t: "pennies", g: true}, {t: " \u2014"}], [{t: "volume hides the leak."}]]},
      {dur: 114, fontSize: 100, lines: [[{t: "You feel busy"}], [{t: "and can't say"}], [{t: "if you "}, {t: "profited", g: true}]]},
      {dur: 108, fontSize: 112, allGreen: true, lines: [[{t: "We find the pennies"}], [{t: "before"}], [{t: "they sink you."}]]},
      {dur: 102, fontSize: 104, lines: [[{t: "See your real margin."}]], cta: CTA},
    ],
  },
  {
    id: "reel-restaurant-5",
    title: "Tip and Payroll Mess",
    cards: [
      {dur: 120, fontSize: 108, lines: [[{t: "Tips, taxes,"}], [{t: "tip credit \u2014"}], [{t: "a compliance minefield."}]]},
      {dur: 120, fontSize: 102, lines: [[{t: "One payroll mistake"}], [{t: "here is an"}], [{t: "audit", g: true}, {t: " later."}]]},
      {dur: 114, fontSize: 100, lines: [[{t: "You're not sure"}], [{t: "your tip math"}], [{t: "is even "}, {t: "legal", g: true}]]},
      {dur: 108, fontSize: 112, allGreen: true, lines: [[{t: "We keep tips and"}], [{t: "payroll"}], [{t: "clean and compliant."}]]},
      {dur: 102, fontSize: 104, lines: [[{t: "Get payroll right."}]], cta: CTA},
    ],
  },
  {
    id: "reel-ecom-1",
    title: "Revenue Isn't Profit",
    cards: [
      {dur: 120, fontSize: 108, lines: [[{t: "Sales are up"}], [{t: "40%."}], [{t: "Profit is... flat?"}]]},
      {dur: 120, fontSize: 102, lines: [[{t: "Ad-fueled revenue"}], [{t: "can "}, {t: "lose", g: true}, {t: " money"}], [{t: "on every order."}]]},
      {dur: 114, fontSize: 100, lines: [[{t: "You've scaled a product"}], [{t: "that "}, {t: "wasn't", g: true}], [{t: "profitable."}]]},
      {dur: 108, fontSize: 112, allGreen: true, lines: [[{t: "We find the SKUs"}], [{t: "that actually"}], [{t: "make money."}]]},
      {dur: 102, fontSize: 104, lines: [[{t: "Know your true margin."}]], cta: CTA},
    ],
  },
  {
    id: "reel-ecom-2",
    title: "Landed-Cost Lie",
    cards: [
      {dur: 120, fontSize: 108, lines: [[{t: "You know the"}], [{t: "unit price."}], [{t: "Not the real cost."}]]},
      {dur: 120, fontSize: 102, lines: [[{t: "Shipping, duties, fees \u2014"}], [{t: "landed cost", g: true}], [{t: "is the true number."}]]},
      {dur: 114, fontSize: 100, lines: [[{t: "Your margins ignore"}], [{t: "everything but"}], [{t: "the "}, {t: "invoice", g: true}]]},
      {dur: 108, fontSize: 112, allGreen: true, lines: [[{t: "We cost every SKU"}], [{t: "all the way"}], [{t: "to your door."}]]},
      {dur: 102, fontSize: 104, lines: [[{t: "Get your real COGS."}]], cta: CTA},
    ],
  },
  {
    id: "reel-ecom-3",
    title: "Return Black Hole",
    cards: [
      {dur: 120, fontSize: 108, lines: [[{t: "The sale counted."}], [{t: "Then it"}], [{t: "came back."}]]},
      {dur: 120, fontSize: 102, lines: [[{t: "Returns quietly "}, {t: "erase", g: true}], [{t: "the profit"}], [{t: "you already booked."}]]},
      {dur: 114, fontSize: 100, lines: [[{t: "You track revenue."}], [{t: "You don't track"}], [{t: "what "}, {t: "came back", g: true}]]},
      {dur: 108, fontSize: 112, allGreen: true, lines: [[{t: "We net out returns"}], [{t: "so profit"}], [{t: "is real."}]]},
      {dur: 102, fontSize: 104, lines: [[{t: "See profit after returns."}]], cta: CTA},
    ],
  },
  {
    id: "reel-ecom-4",
    title: "ROAS Mirage",
    cards: [
      {dur: 120, fontSize: 108, lines: [[{t: "Your ads show"}], [{t: "a 4x return."}], [{t: "Your bank says no."}]]},
      {dur: 120, fontSize: 102, lines: [[{t: "ROAS ignores "}, {t: "COGS", g: true}], [{t: "fees, and"}], [{t: "the stuff that's real."}]]},
      {dur: 114, fontSize: 100, lines: [[{t: "You've scaled spend"}], [{t: "on a number"}], [{t: "that "}, {t: "lies", g: true}]]},
      {dur: 108, fontSize: 112, allGreen: true, lines: [[{t: "We tie ad spend"}], [{t: "to actual profit,"}], [{t: "not ROAS."}]]},
      {dur: 102, fontSize: 104, lines: [[{t: "Measure real ad profit."}]], cta: CTA},
    ],
  },
  {
    id: "reel-ecom-5",
    title: "Marketplace Skim",
    cards: [
      {dur: 120, fontSize: 108, lines: [[{t: "Amazon, Etsy, Shopify \u2014"}], [{t: "everyone"}], [{t: "takes a cut."}]]},
      {dur: 120, fontSize: 102, lines: [[{t: "Platform fees skim"}], [{t: "margin you"}], [{t: "never see", g: true}]]},
      {dur: 114, fontSize: 100, lines: [[{t: "You've never added up"}], [{t: "what the"}], [{t: "middlemen", g: true}, {t: " cost."}]]},
      {dur: 108, fontSize: 112, allGreen: true, lines: [[{t: "We total every"}], [{t: "marketplace fee"}], [{t: "against each sale."}]]},
      {dur: 102, fontSize: 104, lines: [[{t: "Count the platform fees."}]], cta: CTA},
    ],
  },
  {
    id: "reel-agency-1",
    title: "Scope Creep",
    cards: [
      {dur: 120, fontSize: 108, lines: [[{t: "\"Just one more"}], [{t: "round.\""}], [{t: "For the fifth time."}]]},
      {dur: 120, fontSize: 102, lines: [[{t: "Every extra round"}], [{t: "is "}, {t: "unbilled", g: true}, {t: " work"}], [{t: "you agreed to."}]]},
      {dur: 114, fontSize: 100, lines: [[{t: "You've done a project's"}], [{t: "worth of"}], [{t: "free", g: true}, {t: " revisions."}]]},
      {dur: 108, fontSize: 112, allGreen: true, lines: [[{t: "We track scope"}], [{t: "so extras"}], [{t: "hit the invoice."}]]},
      {dur: 102, fontSize: 104, lines: [[{t: "Bill the scope creep."}]], cta: CTA},
    ],
  },
  {
    id: "reel-agency-2",
    title: "Utilization Blind",
    cards: [
      {dur: 120, fontSize: 108, lines: [[{t: "The team feels"}], [{t: "slammed."}], [{t: "Are they billable?"}]]},
      {dur: 120, fontSize: 102, lines: [[{t: "Busy and "}, {t: "billable", g: true}], [{t: "are two very"}], [{t: "different things."}]]},
      {dur: 114, fontSize: 100, lines: [[{t: "You have no idea"}], [{t: "what percent"}], [{t: "is "}, {t: "actually", g: true}, {t: " billed."}]]},
      {dur: 108, fontSize: 112, allGreen: true, lines: [[{t: "We track billable"}], [{t: "hours against"}], [{t: "paid ones."}]]},
      {dur: 102, fontSize: 104, lines: [[{t: "See your utilization."}]], cta: CTA},
    ],
  },
  {
    id: "reel-agency-3",
    title: "Retainer Leak",
    cards: [
      {dur: 120, fontSize: 108, lines: [[{t: "Flat monthly retainer."}], [{t: "Unlimited"}], [{t: "client asks."}]]},
      {dur: 120, fontSize: 102, lines: [[{t: "A retainer without"}], [{t: "limits", g: true}], [{t: "is a slow loss."}]]},
      {dur: 114, fontSize: 100, lines: [[{t: "Some clients cost more"}], [{t: "than they "}, {t: "pay", g: true}], [{t: "You know it."}]]},
      {dur: 108, fontSize: 112, allGreen: true, lines: [[{t: "We show which"}], [{t: "retainers"}], [{t: "actually profit."}]]},
      {dur: 102, fontSize: 104, lines: [[{t: "Fix your retainers."}]], cta: CTA},
    ],
  },
  {
    id: "reel-agency-4",
    title: "Feast or Famine",
    cards: [
      {dur: 120, fontSize: 108, lines: [[{t: "Huge month."}], [{t: "Dead month."}], [{t: "Repeat forever."}]]},
      {dur: 120, fontSize: 102, lines: [[{t: "Lumpy revenue with"}], [{t: "no "}, {t: "reserve", g: true}], [{t: "is a trap."}]]},
      {dur: 114, fontSize: 100, lines: [[{t: "You've spent the"}], [{t: "feast and "}, {t: "starved", g: true}], [{t: "in the famine."}]]},
      {dur: 108, fontSize: 112, allGreen: true, lines: [[{t: "We smooth the swings"}], [{t: "so slow months"}], [{t: "don't sink you."}]]},
      {dur: 102, fontSize: 104, lines: [[{t: "Break the feast-famine cycle."}]], cta: CTA},
    ],
  },
  {
    id: "reel-agency-5",
    title: "Chasing Invoices",
    cards: [
      {dur: 120, fontSize: 108, lines: [[{t: "The work's done."}], [{t: "The invoice?"}], [{t: "\"Following up!\""}]]},
      {dur: 120, fontSize: 102, lines: [[{t: "Net-45 clients turn"}], [{t: "you into their"}], [{t: "free bank", g: true}]]},
      {dur: 114, fontSize: 100, lines: [[{t: "You're owed money"}], [{t: "you've "}, {t: "stopped", g: true}], [{t: "chasing."}]]},
      {dur: 108, fontSize: 112, allGreen: true, lines: [[{t: "We chase the"}], [{t: "invoices so"}], [{t: "you get paid."}]]},
      {dur: 102, fontSize: 104, lines: [[{t: "Get paid on time."}]], cta: CTA},
    ],
  },
  {
    id: "reel-salon-1",
    title: "No-Show Tax",
    cards: [
      {dur: 120, fontSize: 108, lines: [[{t: "Two no-shows today."}], [{t: "That chair"}], [{t: "sat empty."}]]},
      {dur: 120, fontSize: 102, lines: [[{t: "Every no-show is"}], [{t: "revenue", g: true}], [{t: "you can't get back."}]]},
      {dur: 114, fontSize: 100, lines: [[{t: "You've never priced"}], [{t: "what empty"}], [{t: "chairs", g: true}, {t: " cost you."}]]},
      {dur: 108, fontSize: 112, allGreen: true, lines: [[{t: "We put a number"}], [{t: "on no-shows"}], [{t: "and gaps."}]]},
      {dur: 102, fontSize: 104, lines: [[{t: "Stop losing empty chairs."}]], cta: CTA},
    ],
  },
  {
    id: "reel-salon-2",
    title: "Booth-Rent Math",
    cards: [
      {dur: 120, fontSize: 108, lines: [[{t: "You rent chairs"}], [{t: "to stylists. Are"}], [{t: "you making money?"}]]},
      {dur: 120, fontSize: 102, lines: [[{t: "Booth rent that's"}], [{t: "too "}, {t: "low", g: true}], [{t: "loses you money quietly."}]]},
      {dur: 114, fontSize: 100, lines: [[{t: "You set that rent"}], [{t: "on a "}, {t: "feeling", g: true}], [{t: "years ago."}]]},
      {dur: 108, fontSize: 112, allGreen: true, lines: [[{t: "We price the chair"}], [{t: "to actually"}], [{t: "pay you."}]]},
      {dur: 102, fontSize: 104, lines: [[{t: "Price your chairs right."}]], cta: CTA},
    ],
  },
  {
    id: "reel-salon-3",
    title: "Retail-Shelf Leak",
    cards: [
      {dur: 120, fontSize: 108, lines: [[{t: "Shelves full of"}], [{t: "product. Barely"}], [{t: "selling."}]]},
      {dur: 120, fontSize: 102, lines: [[{t: "Retail you don't "}, {t: "move", g: true}], [{t: "is cash"}], [{t: "on a shelf."}]]},
      {dur: 114, fontSize: 100, lines: [[{t: "You reorder product"}], [{t: "you haven't"}], [{t: "counted", g: true}]]},
      {dur: 108, fontSize: 112, allGreen: true, lines: [[{t: "We turn your shelf"}], [{t: "into cash,"}], [{t: "not clutter."}]]},
      {dur: 102, fontSize: 104, lines: [[{t: "Fix your retail margin."}]], cta: CTA},
    ],
  },
  {
    id: "reel-salon-4",
    title: "Tip and Wage Tangle",
    cards: [
      {dur: 120, fontSize: 108, lines: [[{t: "Tips, commission,"}], [{t: "hourly, product \u2014"}], [{t: "payroll's a maze."}]]},
      {dur: 120, fontSize: 102, lines: [[{t: "One wrong split"}], [{t: "and it's a"}], [{t: "compliance", g: true}, {t: " problem."}]]},
      {dur: 114, fontSize: 100, lines: [[{t: "You're not sure"}], [{t: "your pay"}], [{t: "is even "}, {t: "legal", g: true}]]},
      {dur: 108, fontSize: 112, allGreen: true, lines: [[{t: "We untangle"}], [{t: "commission, tips,"}], [{t: "and payroll."}]]},
      {dur: 102, fontSize: 104, lines: [[{t: "Clean up payroll."}]], cta: CTA},
    ],
  },
  {
    id: "reel-salon-5",
    title: "Owner Behind the Chair",
    cards: [
      {dur: 120, fontSize: 108, lines: [[{t: "You're booked solid"}], [{t: "and still can't"}], [{t: "pay yourself."}]]},
      {dur: 120, fontSize: 102, lines: [[{t: "Working the chair"}], [{t: "isn't the same"}], [{t: "as "}, {t: "owning", g: true}, {t: " a business."}]]},
      {dur: 114, fontSize: 100, lines: [[{t: "The salon runs"}], [{t: "on "}, {t: "your", g: true}], [{t: "hands, not systems."}]]},
      {dur: 108, fontSize: 112, allGreen: true, lines: [[{t: "We build it to"}], [{t: "pay you,"}], [{t: "chair or not."}]]},
      {dur: 102, fontSize: 104, lines: [[{t: "Get paid to own it."}]], cta: CTA},
    ],
  },
  {
    id: "reel-dental-1",
    title: "Production vs Collection",
    cards: [
      {dur: 120, fontSize: 108, lines: [[{t: "You produced"}], [{t: "$80k this month."}], [{t: "You collected... less."}]]},
      {dur: 120, fontSize: 102, lines: [[{t: "Production is a number."}], [{t: "Collection", g: true}], [{t: "is the money."}]]},
      {dur: 114, fontSize: 100, lines: [[{t: "You have "}, {t: "claims", g: true}], [{t: "sitting unpaid"}], [{t: "and don't know it."}]]},
      {dur: 108, fontSize: 112, allGreen: true, lines: [[{t: "We chase every"}], [{t: "claim until"}], [{t: "it's collected."}]]},
      {dur: 102, fontSize: 104, lines: [[{t: "Collect what you produce."}]], cta: CTA},
    ],
  },
  {
    id: "reel-dental-2",
    title: "Insurance Float",
    cards: [
      {dur: 120, fontSize: 108, lines: [[{t: "You did the work."}], [{t: "Insurance pays"}], [{t: "in... 45 days? 60?"}]]},
      {dur: 120, fontSize: 102, lines: [[{t: "Slow reimbursement makes"}], [{t: "you the"}], [{t: "free bank", g: true}, {t: " again."}]]},
      {dur: 114, fontSize: 100, lines: [[{t: "You've written off"}], [{t: "claims you just"}], [{t: "gave up", g: true}, {t: " on."}]]},
      {dur: 108, fontSize: 112, allGreen: true, lines: [[{t: "We track every"}], [{t: "claim"}], [{t: "to paid."}]]},
      {dur: 102, fontSize: 104, lines: [[{t: "Stop floating insurance."}]], cta: CTA},
    ],
  },
  {
    id: "reel-dental-3",
    title: "Empty Chair",
    cards: [
      {dur: 120, fontSize: 108, lines: [[{t: "A cancellation."}], [{t: "An empty chair."}], [{t: "An idle hygienist."}]]},
      {dur: 120, fontSize: 102, lines: [[{t: "That open slot is"}], [{t: "overhead", g: true}], [{t: "with no revenue."}]]},
      {dur: 114, fontSize: 100, lines: [[{t: "You pay the room"}], [{t: "and the staff"}], [{t: "either way", g: true}]]},
      {dur: 108, fontSize: 112, allGreen: true, lines: [[{t: "We price the gaps"}], [{t: "so you fill"}], [{t: "the right ones."}]]},
      {dur: 102, fontSize: 104, lines: [[{t: "Fill your schedule profitably."}]], cta: CTA},
    ],
  },
  {
    id: "reel-dental-4",
    title: "Overhead Creep",
    cards: [
      {dur: 120, fontSize: 108, lines: [[{t: "Supplies, labs,"}], [{t: "that new gadget."}], [{t: "It adds up fast."}]]},
      {dur: 120, fontSize: 102, lines: [[{t: "Overhead crept past"}], [{t: "60%", g: true}], [{t: "while you drilled."}]]},
      {dur: 114, fontSize: 100, lines: [[{t: "You haven't checked"}], [{t: "supply costs since"}], [{t: "before COVID", g: true}]]},
      {dur: 108, fontSize: 112, allGreen: true, lines: [[{t: "We watch overhead"}], [{t: "so it stops"}], [{t: "eating you."}]]},
      {dur: 102, fontSize: 104, lines: [[{t: "Cut practice overhead."}]], cta: CTA},
    ],
  },
  {
    id: "reel-dental-5",
    title: "Associate Math",
    cards: [
      {dur: 120, fontSize: 108, lines: [[{t: "You brought on"}], [{t: "an associate."}], [{t: "Are they profitable?"}]]},
      {dur: 120, fontSize: 102, lines: [[{t: "A provider who"}], [{t: "under-produces", g: true}], [{t: "costs you every day."}]]},
      {dur: 114, fontSize: 100, lines: [[{t: "You don't actually"}], [{t: "know if the"}], [{t: "hire "}, {t: "pays", g: true}]]},
      {dur: 108, fontSize: 112, allGreen: true, lines: [[{t: "We show production"}], [{t: "and profit"}], [{t: "per provider."}]]},
      {dur: 102, fontSize: 104, lines: [[{t: "Know your provider profit."}]], cta: CTA},
    ],
  },
  {
    id: "reel-gym-1",
    title: "Ghost Members",
    cards: [
      {dur: 120, fontSize: 108, lines: [[{t: "300 members."}], [{t: "120 actually"}], [{t: "show up."}]]},
      {dur: 120, fontSize: 102, lines: [[{t: "Ghost members feel"}], [{t: "like revenue \u2014 until"}], [{t: "they "}, {t: "cancel", g: true}]]},
      {dur: 114, fontSize: 100, lines: [[{t: "Your \"member count\""}], [{t: "hides your"}], [{t: "real "}, {t: "churn", g: true}]]},
      {dur: 108, fontSize: 112, allGreen: true, lines: [[{t: "We track active"}], [{t: "vs paying"}], [{t: "vs gone."}]]},
      {dur: 102, fontSize: 104, lines: [[{t: "See your real membership."}]], cta: CTA},
    ],
  },
  {
    id: "reel-gym-2",
    title: "January Illusion",
    cards: [
      {dur: 120, fontSize: 108, lines: [[{t: "January's packed."}], [{t: "March is"}], [{t: "a ghost town."}]]},
      {dur: 120, fontSize: 102, lines: [[{t: "A resolution spike"}], [{t: "isn't a"}], [{t: "business", g: true}, {t: " plan."}]]},
      {dur: 114, fontSize: 100, lines: [[{t: "You spend the"}], [{t: "January cash"}], [{t: "by "}, {t: "March", g: true}]]},
      {dur: 108, fontSize: 112, allGreen: true, lines: [[{t: "We smooth the"}], [{t: "seasonal swing"}], [{t: "so you survive spring."}]]},
      {dur: 102, fontSize: 104, lines: [[{t: "Survive the January drop."}]], cta: CTA},
    ],
  },
  {
    id: "reel-gym-3",
    title: "Trainer Utilization",
    cards: [
      {dur: 120, fontSize: 108, lines: [[{t: "Your trainers are"}], [{t: "on the clock."}], [{t: "Are the classes full?"}]]},
      {dur: 120, fontSize: 102, lines: [[{t: "An empty class"}], [{t: "still "}, {t: "pays", g: true}], [{t: "the trainer."}]]},
      {dur: 114, fontSize: 100, lines: [[{t: "You're paying for"}], [{t: "sessions nobody"}], [{t: "booked", g: true}]]},
      {dur: 108, fontSize: 112, allGreen: true, lines: [[{t: "We match trainer"}], [{t: "hours to"}], [{t: "butts in seats."}]]},
      {dur: 102, fontSize: 104, lines: [[{t: "Fill the classes you pay for."}]], cta: CTA},
    ],
  },
  {
    id: "reel-gym-4",
    title: "Rent vs Reality",
    cards: [
      {dur: 120, fontSize: 108, lines: [[{t: "Big space."}], [{t: "Big rent."}], [{t: "Enough members?"}]]},
      {dur: 120, fontSize: 102, lines: [[{t: "Square footage you"}], [{t: "can't "}, {t: "fill", g: true}], [{t: "is a monthly loss."}]]},
      {dur: 114, fontSize: 100, lines: [[{t: "You signed the lease"}], [{t: "on a "}, {t: "dream", g: true}], [{t: "membership count."}]]},
      {dur: 108, fontSize: 112, allGreen: true, lines: [[{t: "We check if the"}], [{t: "space actually"}], [{t: "pays for itself."}]]},
      {dur: 102, fontSize: 104, lines: [[{t: "Right-size your space."}]], cta: CTA},
    ],
  },
  {
    id: "reel-gym-5",
    title: "Price Frozen",
    cards: [
      {dur: 120, fontSize: 108, lines: [[{t: "Costs went up."}], [{t: "Your membership"}], [{t: "price didn't."}]]},
      {dur: 120, fontSize: 102, lines: [[{t: "You're charging "}, {t: "2019", g: true}], [{t: "prices in"}], [{t: "today's economy."}]]},
      {dur: 114, fontSize: 100, lines: [[{t: "You're scared to"}], [{t: "raise it and"}], [{t: "eating", g: true}, {t: " the gap."}]]},
      {dur: 108, fontSize: 112, allGreen: true, lines: [[{t: "We price the"}], [{t: "membership to"}], [{t: "actually profit."}]]},
      {dur: 102, fontSize: 104, lines: [[{t: "Price your memberships right."}]], cta: CTA},
    ],
  },
  {
    id: "reel-realestate-1",
    title: "Commission Rollercoaster",
    cards: [
      {dur: 120, fontSize: 108, lines: [[{t: "Huge closing month."}], [{t: "Then nothing"}], [{t: "for 90 days."}]]},
      {dur: 120, fontSize: 102, lines: [[{t: "Commission income with"}], [{t: "no "}, {t: "reserve", g: true}], [{t: "is a trap."}]]},
      {dur: 114, fontSize: 100, lines: [[{t: "You spent the"}], [{t: "big check before"}], [{t: "the "}, {t: "dry spell", g: true}]]},
      {dur: 108, fontSize: 112, allGreen: true, lines: [[{t: "We smooth the"}], [{t: "commissions into"}], [{t: "a steady paycheck."}]]},
      {dur: 102, fontSize: 104, lines: [[{t: "Steady your income."}]], cta: CTA},
    ],
  },
  {
    id: "reel-realestate-2",
    title: "1099 Surprise",
    cards: [
      {dur: 120, fontSize: 108, lines: [[{t: "Nobody withholds"}], [{t: "taxes from"}], [{t: "your commission."}]]},
      {dur: 120, fontSize: 102, lines: [[{t: "That whole check"}], [{t: "isn't "}, {t: "yours", g: true}], [{t: "The IRS wants a cut."}]]},
      {dur: 114, fontSize: 100, lines: [[{t: "You've been "}, {t: "blindsided", g: true}], [{t: "by a tax bill"}], [{t: "in April."}]]},
      {dur: 108, fontSize: 112, allGreen: true, lines: [[{t: "We set aside"}], [{t: "taxes before"}], [{t: "you spend it."}]]},
      {dur: 102, fontSize: 104, lines: [[{t: "Never get taxed off guard."}]], cta: CTA},
    ],
  },
  {
    id: "reel-realestate-3",
    title: "Deductions Driving By",
    cards: [
      {dur: 120, fontSize: 108, lines: [[{t: "Miles, marketing,"}], [{t: "staging, meals."}], [{t: "All deductible."}]]},
      {dur: 120, fontSize: 102, lines: [[{t: "Every untracked mile"}], [{t: "is a "}, {t: "deduction", g: true}], [{t: "you gave away."}]]},
      {dur: 114, fontSize: 100, lines: [[{t: "Your write-offs live"}], [{t: "in a "}, {t: "glovebox", g: true}], [{t: "and your memory."}]]},
      {dur: 108, fontSize: 112, allGreen: true, lines: [[{t: "We capture every"}], [{t: "deduction you"}], [{t: "drive past."}]]},
      {dur: 102, fontSize: 104, lines: [[{t: "Keep more per closing."}]], cta: CTA},
    ],
  },
  {
    id: "reel-realestate-4",
    title: "Split Confusion",
    cards: [
      {dur: 120, fontSize: 108, lines: [[{t: "Brokerage split."}], [{t: "Team split."}], [{t: "Referral fee."}]]},
      {dur: 120, fontSize: 102, lines: [[{t: "After every split,"}], [{t: "what's "}, {t: "actually", g: true}], [{t: "yours?"}]]},
      {dur: 114, fontSize: 100, lines: [[{t: "You couldn't say"}], [{t: "your real"}], [{t: "take-home", g: true}, {t: " per deal."}]]},
      {dur: 108, fontSize: 112, allGreen: true, lines: [[{t: "We show net"}], [{t: "per closing,"}], [{t: "after every split."}]]},
      {dur: 102, fontSize: 104, lines: [[{t: "Know your real take-home."}]], cta: CTA},
    ],
  },
  {
    id: "reel-realestate-5",
    title: "Feast, No Reserve",
    cards: [
      {dur: 120, fontSize: 108, lines: [[{t: "Best year ever."}], [{t: "Zero"}], [{t: "saved."}]]},
      {dur: 120, fontSize: 102, lines: [[{t: "A great year with"}], [{t: "no "}, {t: "reserve", g: true}], [{t: "is one slow quarter from trouble."}]]},
      {dur: 114, fontSize: 100, lines: [[{t: "You've been "}, {t: "one", g: true}], [{t: "dry spell"}], [{t: "from panic. Admit it."}]]},
      {dur: 108, fontSize: 112, allGreen: true, lines: [[{t: "We build a reserve"}], [{t: "so slow months"}], [{t: "don't scare you."}]]},
      {dur: 102, fontSize: 104, lines: [[{t: "Build your cushion."}]], cta: CTA},
    ],
  },
  {
    id: "reel-trucking-1",
    title: "Cost Per Mile",
    cards: [
      {dur: 120, fontSize: 108, lines: [[{t: "You know your"}], [{t: "rate per mile."}], [{t: "Your cost per mile?"}]]},
      {dur: 120, fontSize: 102, lines: [[{t: "If you don't know"}], [{t: "your "}, {t: "cost", g: true}, {t: " per mile,"}], [{t: "every load's a guess."}]]},
      {dur: 114, fontSize: 100, lines: [[{t: "You've hauled loads"}], [{t: "that "}, {t: "lost", g: true}], [{t: "money and felt busy."}]]},
      {dur: 108, fontSize: 112, allGreen: true, lines: [[{t: "We nail your"}], [{t: "cost per mile"}], [{t: "down to the cent."}]]},
      {dur: 102, fontSize: 104, lines: [[{t: "Know your cost per mile."}]], cta: CTA},
    ],
  },
  {
    id: "reel-trucking-2",
    title: "Fuel Bleed",
    cards: [
      {dur: 120, fontSize: 108, lines: [[{t: "Fuel's your"}], [{t: "biggest cost."}], [{t: "And least watched."}]]},
      {dur: 120, fontSize: 102, lines: [[{t: "A few cents a gallon,"}], [{t: "every mile", g: true}], [{t: "is real money."}]]},
      {dur: 114, fontSize: 100, lines: [[{t: "You've never"}], [{t: "tracked fuel"}], [{t: "against "}, {t: "revenue", g: true}]]},
      {dur: 108, fontSize: 112, allGreen: true, lines: [[{t: "We watch fuel"}], [{t: "as a percent"}], [{t: "of every load."}]]},
      {dur: 102, fontSize: 104, lines: [[{t: "Control your fuel spend."}]], cta: CTA},
    ],
  },
  {
    id: "reel-trucking-3",
    title: "Breakdown Reserve",
    cards: [
      {dur: 120, fontSize: 108, lines: [[{t: "The truck runs great."}], [{t: "Until"}], [{t: "it doesn't."}]]},
      {dur: 120, fontSize: 102, lines: [[{t: "No maintenance reserve"}], [{t: "means one "}, {t: "breakdown", g: true}], [{t: "= a crisis."}]]},
      {dur: 114, fontSize: 100, lines: [[{t: "You've put a repair"}], [{t: "on a "}, {t: "credit card", g: true}], [{t: "and prayed."}]]},
      {dur: 108, fontSize: 112, allGreen: true, lines: [[{t: "We build a reserve"}], [{t: "so the next"}], [{t: "repair isn't a panic."}]]},
      {dur: 102, fontSize: 104, lines: [[{t: "Fund the next breakdown."}]], cta: CTA},
    ],
  },
  {
    id: "reel-trucking-4",
    title: "Factoring Skim",
    cards: [
      {dur: 120, fontSize: 108, lines: [[{t: "You factor invoices"}], [{t: "to get paid"}], [{t: "today."}]]},
      {dur: 120, fontSize: 102, lines: [[{t: "That fast cash"}], [{t: "costs you"}], [{t: "3-5%", g: true}, {t: " a load."}]]},
      {dur: 114, fontSize: 100, lines: [[{t: "You've never added"}], [{t: "up what"}], [{t: "factoring", g: true}, {t: " costs a year."}]]},
      {dur: 108, fontSize: 112, allGreen: true, lines: [[{t: "We total the"}], [{t: "factoring fees"}], [{t: "against the cash."}]]},
      {dur: 102, fontSize: 104, lines: [[{t: "Count your factoring cost."}]], cta: CTA},
    ],
  },
  {
    id: "reel-trucking-5",
    title: "Owner-Op Take-Home",
    cards: [
      {dur: 120, fontSize: 108, lines: [[{t: "The truck grosses"}], [{t: "plenty."}], [{t: "So why are you broke?"}]]},
      {dur: 120, fontSize: 102, lines: [[{t: "Gross isn't yours."}], [{t: "After costs,"}], [{t: "net", g: true}, {t: " is the number."}]]},
      {dur: 114, fontSize: 100, lines: [[{t: "You've measured success"}], [{t: "by "}, {t: "gross", g: true}], [{t: "and stayed broke."}]]},
      {dur: 108, fontSize: 112, allGreen: true, lines: [[{t: "We show what"}], [{t: "you actually"}], [{t: "take home per mile."}]]},
      {dur: 102, fontSize: 104, lines: [[{t: "See your real take-home."}]], cta: CTA},
    ],
  }
];
