/**
 * carousels.ts — LOCKED carousel copy, 30 entries. Render it, don't rewrite it.
 * Cover art files live in public/covers/ (one per `cover.image`).
 */
import {CarouselData} from './Carousel';

const CTA = 'Free Cash Flow Dashboard';

export const CAROUSELS: CarouselData[] = [
  {
    id: "carousel-busy-1",
    title: "Busy All Year, Still Broke",
    chip: "Busy ≠ Profitable",
    cover: {image: "busy-1.jpg", headline: [[{t: "Busy all year."}], [{t: "Still broke."}]]},
    slides: [
      {dur: 1, fontSize: 96, lines: [[{t: "Being booked solid"}], [{t: "is "}, {t: "not the same", g: true}], [{t: "as being paid."}]]},
      {dur: 1, fontSize: 92, lines: [[{t: "More revenue just"}], [{t: "bought you a bigger"}], [{t: "version of broke.", g: true}]]},
      {dur: 1, fontSize: 94, lines: [[{t: "Every job hides"}], [{t: "a small loss you"}], [{t: "see at year-end.", g: true}]]},
      {dur: 1, fontSize: 100, lines: [[{t: "We cost each job"}], [{t: "while it's live,"}], [{t: "so busy means paid."}]], allGreen: true},
      {dur: 1, fontSize: 100, lines: [[{t: "Turn motion"}], [{t: "into margin."}]], cta: CTA},
    ],
  },
  {
    id: "carousel-bank",
    title: "Money In The Bank Isn't Profit",
    chip: "Money In The Bank",
    cover: {image: "bank.jpg", headline: [[{t: "Money in the bank"}], [{t: "isn't profit."}]]},
    slides: [
      {dur: 1, fontSize: 94, lines: [[{t: "That balance "}, {t: "owes", g: true}], [{t: "taxes, payroll,"}], [{t: "and vendors."}]]},
      {dur: 1, fontSize: 96, lines: [[{t: "You spent money"}], [{t: "that was "}, {t: "never yours.", g: true}]]},
      {dur: 1, fontSize: 94, lines: [[{t: "A big balance today"}], [{t: "is next month's"}], [{t: "panic.", g: true}]]},
      {dur: 1, fontSize: 100, lines: [[{t: "We show what's"}], [{t: "actually yours"}], [{t: "to keep."}]], allGreen: true},
      {dur: 1, fontSize: 98, lines: [[{t: "Know your"}], [{t: "real number."}]], cta: CTA},
    ],
  },
  {
    id: "carousel-revenue-vanity",
    title: "Revenue Is Vanity",
    chip: "Revenue vs. Cash",
    cover: {image: "revenue-vanity.jpg", headline: [[{t: "Revenue is vanity."}], [{t: "Cash is survival."}]]},
    slides: [
      {dur: 1, fontSize: 94, lines: [[{t: "Big sales feel great"}], [{t: "until payroll", g: true}], [{t: "clears."}]]},
      {dur: 1, fontSize: 94, lines: [[{t: "You chased the top"}], [{t: "line and "}, {t: "starved", g: true}], [{t: "the bottom."}]]},
      {dur: 1, fontSize: 98, lines: [[{t: "Revenue is a story."}], [{t: "Cash is "}, {t: "the ending.", g: true}]]},
      {dur: 1, fontSize: 100, lines: [[{t: "We manage the cash,"}], [{t: "not just"}], [{t: "the headline."}]], allGreen: true},
      {dur: 1, fontSize: 100, lines: [[{t: "Protect the cash."}]], cta: CTA},
    ],
  },
  {
    id: "carousel-profit-opinion",
    title: "Profit Is An Opinion",
    chip: "Profit Is An Opinion",
    cover: {image: "profit-opinion.jpg", headline: [[{t: "Profit is an opinion."}], [{t: "Cash is a fact."}]]},
    slides: [
      {dur: 1, fontSize: 92, lines: [[{t: "Your P&L can smile"}], [{t: "while your account"}], [{t: "cries.", g: true}]]},
      {dur: 1, fontSize: 96, lines: [[{t: "Accrual math "}, {t: "hid", g: true}], [{t: "a cash-flow"}], [{t: "problem."}]]},
      {dur: 1, fontSize: 96, lines: [[{t: "Paper profit"}], [{t: "doesn't make", g: true}], [{t: "payroll.", g: true}]]},
      {dur: 1, fontSize: 100, lines: [[{t: "We track both,"}], [{t: "so nothing"}], [{t: "lies to you."}]], allGreen: true},
      {dur: 1, fontSize: 102, lines: [[{t: "See the truth."}]], cta: CTA},
    ],
  },
  {
    id: "carousel-pricing",
    title: "You're Guessing",
    chip: "You're Guessing",
    cover: {image: "pricing.jpg", headline: [[{t: "You're not too"}], [{t: "expensive."}], [{t: "You're guessing."}]]},
    slides: [
      {dur: 1, fontSize: 92, lines: [[{t: "A price from your gut"}], [{t: "isn't a strategy.", g: true}]]},
      {dur: 1, fontSize: 96, lines: [[{t: "You've been"}], [{t: "underpricing", g: true}], [{t: "to feel safe."}]]},
      {dur: 1, fontSize: 94, lines: [[{t: "Cheap wins the job"}], [{t: "and "}, {t: "loses the year.", g: true}]]},
      {dur: 1, fontSize: 100, lines: [[{t: "We price from your"}], [{t: "real costs,"}], [{t: "not fear."}]], allGreen: true},
      {dur: 1, fontSize: 100, lines: [[{t: "Price with proof."}]], cta: CTA},
    ],
  },
  {
    id: "carousel-taxes",
    title: "The IRS Isn't A Surprise",
    chip: "The IRS Isn't A Surprise",
    cover: {image: "taxes.jpg", headline: [[{t: "The IRS isn't"}], [{t: "a surprise."}], [{t: "You didn't look."}]]},
    slides: [
      {dur: 1, fontSize: 94, lines: [[{t: "The bill was always"}], [{t: "coming. You"}], [{t: "looked away.", g: true}]]},
      {dur: 1, fontSize: 96, lines: [[{t: "You spent the"}], [{t: "tax money", g: true}], [{t: "in March."}]]},
      {dur: 1, fontSize: 96, lines: [[{t: "Every sale quietly"}], [{t: "owes a slice.", g: true}]]},
      {dur: 1, fontSize: 98, lines: [[{t: "We set the tax aside"}], [{t: "before you"}], [{t: "can spend it."}]], allGreen: true},
      {dur: 1, fontSize: 98, lines: [[{t: "No April surprises."}]], cta: CTA},
    ],
  },
  {
    id: "carousel-subscriptions",
    title: "Subscribed To Broke",
    chip: "Subscribed To Broke",
    cover: {image: "subscriptions.jpg", headline: [[{t: "You're subscribed"}], [{t: "to being broke."}]]},
    slides: [
      {dur: 1, fontSize: 100, lines: [[{t: "Nine tools."}], [{t: "You use "}, {t: "three.", g: true}]]},
      {dur: 1, fontSize: 96, lines: [[{t: "You forgot", g: true}], [{t: "you were paying"}], [{t: "for half."}]]},
      {dur: 1, fontSize: 96, lines: [[{t: "Small charges are"}], [{t: "still a "}, {t: "big leak.", g: true}]]},
      {dur: 1, fontSize: 98, lines: [[{t: "We hunt the"}], [{t: "auto-renewals you"}], [{t: "stopped noticing."}]], allGreen: true},
      {dur: 1, fontSize: 100, lines: [[{t: "Cancel the leak."}]], cta: CTA},
    ],
  },
  {
    id: "carousel-owner-pay",
    title: "Everyone But You",
    chip: "Everyone But You",
    cover: {image: "owner-pay.jpg", headline: [[{t: "Everyone got paid."}], [{t: "Except you."}]]},
    slides: [
      {dur: 1, fontSize: 92, lines: [[{t: "Owner pay is not"}], [{t: "'whatever's left.'", g: true}]]},
      {dur: 1, fontSize: 94, lines: [[{t: "You funded the"}], [{t: "business with your"}], [{t: "own paycheck.", g: true}]]},
      {dur: 1, fontSize: 94, lines: [[{t: "A business that"}], [{t: "can't pay you"}], [{t: "isn't working.", g: true}]]},
      {dur: 1, fontSize: 98, lines: [[{t: "We pay the owner"}], [{t: "like a real,"}], [{t: "planned expense."}]], allGreen: true},
      {dur: 1, fontSize: 98, lines: [[{t: "Pay yourself first."}]], cta: CTA},
    ],
  },
  {
    id: "carousel-growth-trap",
    title: "You Scaled The Chaos",
    chip: "You Scaled The Chaos",
    cover: {image: "growth-trap.jpg", headline: [[{t: "You scaled the chaos,"}], [{t: "not the profit."}]]},
    slides: [
      {dur: 1, fontSize: 96, lines: [[{t: "Double the revenue,"}], [{t: "double the mess.", g: true}]]},
      {dur: 1, fontSize: 94, lines: [[{t: "You grew everything"}], [{t: "but the "}, {t: "bank balance.", g: true}]]},
      {dur: 1, fontSize: 92, lines: [[{t: "Growth without"}], [{t: "margin is just"}], [{t: "faster losing.", g: true}]]},
      {dur: 1, fontSize: 100, lines: [[{t: "We grow the number"}], [{t: "that matters:"}], [{t: "margin."}]], allGreen: true},
      {dur: 1, fontSize: 100, lines: [[{t: "Scale the profit."}]], cta: CTA},
    ],
  },
  {
    id: "carousel-discount",
    title: "Every Discount Is A Tip",
    chip: "Every Discount Is A Tip",
    cover: {image: "discount.jpg", headline: [[{t: "Every discount is a tip"}], [{t: "you paid"}], [{t: "the customer."}]]},
    slides: [
      {dur: 1, fontSize: 94, lines: [[{t: "10% off can be"}], [{t: "40% of", g: true}], [{t: "your margin.", g: true}]]},
      {dur: 1, fontSize: 94, lines: [[{t: "You discounted to"}], [{t: "close, and closed"}], [{t: "on "}, {t: "a loss.", g: true}]]},
      {dur: 1, fontSize: 96, lines: [[{t: "Price cuts are easy."}], [{t: "Earning it back"}], [{t: "isn't.", g: true}]]},
      {dur: 1, fontSize: 100, lines: [[{t: "We show what a"}], [{t: "discount actually"}], [{t: "costs you."}]], allGreen: true},
      {dur: 1, fontSize: 98, lines: [[{t: "Discount on purpose."}]], cta: CTA},
    ],
  },
  {
    id: "carousel-shoebox",
    title: "The Shoebox Isn't A Strategy",
    chip: "The Shoebox Isn't A Strategy",
    cover: {image: "shoebox.jpg", headline: [[{t: "The shoebox"}], [{t: "isn't a strategy."}]]},
    slides: [
      {dur: 1, fontSize: 94, lines: [[{t: "A year of receipts"}], [{t: "is "}, {t: "not bookkeeping.", g: true}]]},
      {dur: 1, fontSize: 94, lines: [[{t: "You're deciding"}], [{t: "blind", g: true}, {t: " for"}], [{t: "eleven months."}]]},
      {dur: 1, fontSize: 96, lines: [[{t: "By tax time,"}], [{t: "it's "}, {t: "too late", g: true}], [{t: "to fix."}]]},
      {dur: 1, fontSize: 100, lines: [[{t: "We keep the books"}], [{t: "current,"}], [{t: "all year."}]], allGreen: true},
      {dur: 1, fontSize: 100, lines: [[{t: "Ditch the shoebox."}]], cta: CTA},
    ],
  },
  {
    id: "carousel-friday",
    title: "Broke On Friday",
    chip: "Broke On Friday",
    cover: {image: "friday.jpg", headline: [[{t: "Profitable on paper."}], [{t: "Broke on Friday."}]]},
    slides: [
      {dur: 1, fontSize: 94, lines: [[{t: "Profit and cash"}], [{t: "don't arrive"}], [{t: "the same day.", g: true}]]},
      {dur: 1, fontSize: 96, lines: [[{t: "You made money"}], [{t: "you "}, {t: "can't touch", g: true}], [{t: "yet."}]]},
      {dur: 1, fontSize: 94, lines: [[{t: "Timing", g: true}, {t: " is what"}], [{t: "actually sinks"}], [{t: "businesses."}]]},
      {dur: 1, fontSize: 98, lines: [[{t: "We forecast the"}], [{t: "crunch before"}], [{t: "it hits."}]], allGreen: true},
      {dur: 1, fontSize: 98, lines: [[{t: "Never miss payroll."}]], cta: CTA},
    ],
  },
  {
    id: "carousel-cant-see",
    title: "Can't Cut What You Can't See",
    chip: "You Can't See It",
    cover: {image: "cant-see.jpg", headline: [[{t: "You can't cut"}], [{t: "what you can't see."}]]},
    slides: [
      {dur: 1, fontSize: 94, lines: [[{t: "You can't fix"}], [{t: "a number you"}], [{t: "never look at.", g: true}]]},
      {dur: 1, fontSize: 94, lines: [[{t: "The waste has"}], [{t: "been hiding in"}], [{t: "plain sight.", g: true}]]},
      {dur: 1, fontSize: 94, lines: [[{t: "What you don't"}], [{t: "measure, you"}], [{t: "fund forever.", g: true}]]},
      {dur: 1, fontSize: 100, lines: [[{t: "We put every dollar"}], [{t: "on one"}], [{t: "screen."}]], allGreen: true},
      {dur: 1, fontSize: 104, lines: [[{t: "See it all."}]], cta: CTA},
    ],
  },
  {
    id: "carousel-margin",
    title: "Margin Feeds Your Family",
    chip: "Margin Feeds Your Family",
    cover: {image: "margin.jpg", headline: [[{t: "Revenue feeds ego."}], [{t: "Margin feeds"}], [{t: "your family."}]]},
    slides: [
      {dur: 1, fontSize: 98, lines: [[{t: "Nobody", g: true}, {t: " takes"}], [{t: "home revenue."}]]},
      {dur: 1, fontSize: 92, lines: [[{t: "You bragged about"}], [{t: "sales and "}, {t: "skipped", g: true}], [{t: "a paycheck.", g: true}]]},
      {dur: 1, fontSize: 96, lines: [[{t: "Margin is the only"}], [{t: "number "}, {t: "you keep.", g: true}]]},
      {dur: 1, fontSize: 98, lines: [[{t: "We build around"}], [{t: "margin,"}], [{t: "not noise."}]], allGreen: true},
      {dur: 1, fontSize: 98, lines: [[{t: "Grow what you keep."}]], cta: CTA},
    ],
  },
  {
    id: "carousel-forecast",
    title: "Hope Is Not A Forecast",
    chip: "Hope Is Not A Forecast",
    cover: {image: "forecast.jpg", headline: [[{t: "Hope is not"}], [{t: "a forecast."}]]},
    slides: [
      {dur: 1, fontSize: 96, lines: [[{t: "'It'll pick up'"}], [{t: "is "}, {t: "not a plan.", g: true}]]},
      {dur: 1, fontSize: 92, lines: [[{t: "You fly into every"}], [{t: "slow season"}], [{t: "blind.", g: true}]]},
      {dur: 1, fontSize: 94, lines: [[{t: "A forecast turns"}], [{t: "surprises into"}], [{t: "decisions.", g: true}]]},
      {dur: 1, fontSize: 100, lines: [[{t: "We map the next"}], [{t: "90 days so"}], [{t: "you can steer."}]], allGreen: true},
      {dur: 1, fontSize: 100, lines: [[{t: "Forecast, don't hope."}]], cta: CTA},
    ],
  },
  {
    id: "carousel-late-invoices",
    title: "Your Clients' Free Bank",
    chip: "Your Clients' Free Bank",
    cover: {image: "late-invoices.jpg", headline: [[{t: "Your clients use you"}], [{t: "as a bank."}]]},
    slides: [
      {dur: 1, fontSize: 96, lines: [[{t: "Net 30 became"}], [{t: "net "}, {t: "whenever.", g: true}]]},
      {dur: 1, fontSize: 94, lines: [[{t: "You financed their"}], [{t: "business with"}], [{t: "yours.", g: true}]]},
      {dur: 1, fontSize: 90, lines: [[{t: "Unpaid invoices are"}], [{t: "cash you "}, {t: "already", g: true}], [{t: "spent earning.", g: true}]]},
      {dur: 1, fontSize: 98, lines: [[{t: "We chase every"}], [{t: "dollar owed"}], [{t: "until it lands."}]], allGreen: true},
      {dur: 1, fontSize: 100, lines: [[{t: "Get paid faster."}]], cta: CTA},
    ],
  },
  {
    id: "carousel-breakeven",
    title: "You Don't Know Break-Even",
    chip: "You Don't Know Break-Even",
    cover: {image: "breakeven.jpg", headline: [[{t: "You don't know"}], [{t: "your break-even."}]]},
    slides: [
      {dur: 1, fontSize: 98, lines: [[{t: "So every sale"}], [{t: "is "}, {t: "a guess.", g: true}]]},
      {dur: 1, fontSize: 94, lines: [[{t: "Some months you"}], [{t: "worked just to"}], [{t: "stay flat.", g: true}]]},
      {dur: 1, fontSize: 94, lines: [[{t: "Not knowing the line"}], [{t: "means crossing it"}], [{t: "blind.", g: true}]]},
      {dur: 1, fontSize: 100, lines: [[{t: "We pin the exact"}], [{t: "number you"}], [{t: "must clear."}]], allGreen: true},
      {dur: 1, fontSize: 104, lines: [[{t: "Know your line."}]], cta: CTA},
    ],
  },
  {
    id: "carousel-reinvest",
    title: "The Truck Didn't Buy You Anything",
    chip: "It Didn't Buy You Anything",
    cover: {image: "reinvest.jpg", headline: [[{t: "You bought the truck."}], [{t: "It bought you"}], [{t: "nothing."}]]},
    slides: [
      {dur: 1, fontSize: 94, lines: [[{t: "New gear feels like"}], [{t: "growth. It's "}, {t: "a bill.", g: true}]]},
      {dur: 1, fontSize: 94, lines: [[{t: "You reinvested into"}], [{t: "more overhead.", g: true}]]},
      {dur: 1, fontSize: 96, lines: [[{t: "An asset should"}], [{t: "earn,", g: true}, {t: " not"}], [{t: "just impress."}]]},
      {dur: 1, fontSize: 100, lines: [[{t: "We check if it pays"}], [{t: "before"}], [{t: "you buy it."}]], allGreen: true},
      {dur: 1, fontSize: 100, lines: [[{t: "Invest for return."}]], cta: CTA},
    ],
  },
  {
    id: "carousel-contractor-eulogy",
    title: "Margin At Year-End Is A Eulogy",
    chip: "6 Tips For Job Costing",
    cover: {image: "contractor-eulogy.jpg", headline: [[{t: "Margin found"}], [{t: "at year-end"}], [{t: "is a eulogy."}]]},
    slides: [
      {dur: 1, fontSize: 92, lines: [[{t: "A job you can't"}], [{t: "measure is a job"}], [{t: "you "}, {t: "can't price.", g: true}]]},
      {dur: 1, fontSize: 94, lines: [[{t: "You bid the next one"}], [{t: "off "}, {t: "a feeling.", g: true}]]},
      {dur: 1, fontSize: 92, lines: [[{t: "The loss was decided"}], [{t: "the day"}], [{t: "you quoted.", g: true}]]},
      {dur: 1, fontSize: 98, lines: [[{t: "We cost the job"}], [{t: "while the crew's"}], [{t: "still on site."}]], allGreen: true},
      {dur: 1, fontSize: 100, lines: [[{t: "Know it by Tuesday."}]], cta: CTA},
    ],
  },
  {
    id: "carousel-restaurant",
    title: "Full Tables, Empty Account",
    chip: "Full Tables, Empty Account",
    cover: {image: "restaurant.jpg", headline: [[{t: "Full tables."}], [{t: "Empty account."}]]},
    slides: [
      {dur: 1, fontSize: 94, lines: [[{t: "A packed room can"}], [{t: "still "}, {t: "lose money.", g: true}]]},
      {dur: 1, fontSize: 96, lines: [[{t: "Food and labor"}], [{t: "ate", g: true}, {t: " the whole"}], [{t: "night."}]]},
      {dur: 1, fontSize: 92, lines: [[{t: "Covers don't matter"}], [{t: "if "}, {t: "the plate", g: true}], [{t: "loses money."}]]},
      {dur: 1, fontSize: 98, lines: [[{t: "We price the menu"}], [{t: "off real"}], [{t: "plate costs."}]], allGreen: true},
      {dur: 1, fontSize: 98, lines: [[{t: "Fill tables that pay."}]], cta: CTA},
    ],
  },
  {
    id: "carousel-ecom",
    title: "Sold Out, Still Lost",
    chip: "Sold Out, Still Lost",
    cover: {image: "ecom.jpg", headline: [[{t: "Sold out."}], [{t: "Still lost money."}]]},
    slides: [
      {dur: 1, fontSize: 94, lines: [[{t: "Ads, fees, shipping"}], [{t: "ate the margin.", g: true}]]},
      {dur: 1, fontSize: 94, lines: [[{t: "You celebrated"}], [{t: "revenue you"}], [{t: "never kept.", g: true}]]},
      {dur: 1, fontSize: 94, lines: [[{t: "A best-seller can be"}], [{t: "your "}, {t: "worst product.", g: true}]]},
      {dur: 1, fontSize: 100, lines: [[{t: "We find the true"}], [{t: "margin"}], [{t: "per SKU."}]], allGreen: true},
      {dur: 1, fontSize: 102, lines: [[{t: "Sell what profits."}]], cta: CTA},
    ],
  },
  {
    id: "carousel-salon",
    title: "Booked Solid, Broke Solid",
    chip: "Booked Solid, Broke Solid",
    cover: {image: "salon.jpg", headline: [[{t: "Booked solid."}], [{t: "Broke solid."}]]},
    slides: [
      {dur: 1, fontSize: 92, lines: [[{t: "A full chair isn't"}], [{t: "a "}, {t: "full bank account.", g: true}]]},
      {dur: 1, fontSize: 94, lines: [[{t: "Product and rent"}], [{t: "quietly "}, {t: "took the tips.", g: true}]]},
      {dur: 1, fontSize: 94, lines: [[{t: "Busy hands don't"}], [{t: "guarantee a"}], [{t: "paid owner.", g: true}]]},
      {dur: 1, fontSize: 98, lines: [[{t: "We turn a full book"}], [{t: "into real"}], [{t: "take-home."}]], allGreen: true},
      {dur: 1, fontSize: 100, lines: [[{t: "Book it and keep it."}]], cta: CTA},
    ],
  },
  {
    id: "carousel-agency",
    title: "Great Work, Terrible Margins",
    chip: "Great Work, Terrible Margins",
    cover: {image: "agency.jpg", headline: [[{t: "Great work."}], [{t: "Terrible margins."}]]},
    slides: [
      {dur: 1, fontSize: 94, lines: [[{t: "Scope crept and"}], [{t: "nobody billed it.", g: true}]]},
      {dur: 1, fontSize: 94, lines: [[{t: "You "}, {t: "over-delivered", g: true}], [{t: "your profit"}], [{t: "away."}]]},
      {dur: 1, fontSize: 94, lines: [[{t: "Every 'quick favor'"}], [{t: "had "}, {t: "a real cost.", g: true}]]},
      {dur: 1, fontSize: 98, lines: [[{t: "We price by value"}], [{t: "and track it"}], [{t: "by project."}]], allGreen: true},
      {dur: 1, fontSize: 100, lines: [[{t: "Bill what it's worth."}]], cta: CTA},
    ],
  },
  {
    id: "carousel-trucking",
    title: "The Truck Moved, Money Didn't",
    chip: "The Money Didn't Move",
    cover: {image: "trucking.jpg", headline: [[{t: "The truck moved."}], [{t: "The money didn't."}]]},
    slides: [
      {dur: 1, fontSize: 92, lines: [[{t: "Fuel, maintenance,"}], [{t: "deadhead "}, {t: "ate the rate.", g: true}]]},
      {dur: 1, fontSize: 96, lines: [[{t: "You ran loaded miles"}], [{t: "for "}, {t: "a loss.", g: true}]]},
      {dur: 1, fontSize: 94, lines: [[{t: "Revenue "}, {t: "per mile", g: true}], [{t: "is the only number"}], [{t: "that matters."}]]},
      {dur: 1, fontSize: 100, lines: [[{t: "We cost every load"}], [{t: "before"}], [{t: "you roll."}]], allGreen: true},
      {dur: 1, fontSize: 102, lines: [[{t: "Haul for profit."}]], cta: CTA},
    ],
  },
  {
    id: "carousel-dental",
    title: "Full Schedule, Thin Profit",
    chip: "Full Schedule, Thin Profit",
    cover: {image: "dental.jpg", headline: [[{t: "Full schedule."}], [{t: "Thin profit."}]]},
    slides: [
      {dur: 1, fontSize: 98, lines: [[{t: "Production"}], [{t: "isn't "}, {t: "collection.", g: true}]]},
      {dur: 1, fontSize: 94, lines: [[{t: "Insurance write-offs"}], [{t: "quietly "}, {t: "bled you.", g: true}]]},
      {dur: 1, fontSize: 94, lines: [[{t: "A booked chair can"}], [{t: "still run "}, {t: "at a loss.", g: true}]]},
      {dur: 1, fontSize: 98, lines: [[{t: "We track collections,"}], [{t: "overhead,"}], [{t: "and take-home."}]], allGreen: true},
      {dur: 1, fontSize: 100, lines: [[{t: "Fill it profitably."}]], cta: CTA},
    ],
  },
  {
    id: "carousel-gym",
    title: "Members Up, Cash Down",
    chip: "Members Up, Cash Down",
    cover: {image: "gym.jpg", headline: [[{t: "Members up."}], [{t: "Cash down."}]]},
    slides: [
      {dur: 1, fontSize: 92, lines: [[{t: "Sign-ups aren't the"}], [{t: "same as "}, {t: "kept members.", g: true}]]},
      {dur: 1, fontSize: 98, lines: [[{t: "Churn", g: true}, {t: " ate every"}], [{t: "new join."}]]},
      {dur: 1, fontSize: 96, lines: [[{t: "Growth means"}], [{t: "nothing if "}, {t: "they leave.", g: true}]]},
      {dur: 1, fontSize: 98, lines: [[{t: "We track the numbers"}], [{t: "that keep the"}], [{t: "doors open."}]], allGreen: true},
      {dur: 1, fontSize: 102, lines: [[{t: "Grow retention."}]], cta: CTA},
    ],
  },
  {
    id: "carousel-realestate",
    title: "Commission Rich, Cash Poor",
    chip: "Commission Rich, Cash Poor",
    cover: {image: "realestate.jpg", headline: [[{t: "Commission rich."}], [{t: "Cash poor."}]]},
    slides: [
      {dur: 1, fontSize: 94, lines: [[{t: "Big checks, months"}], [{t: "apart, "}, {t: "spent fast.", g: true}]]},
      {dur: 1, fontSize: 96, lines: [[{t: "You lived on"}], [{t: "the last closing.", g: true}]]},
      {dur: 1, fontSize: 94, lines: [[{t: "Lumpy income needs"}], [{t: "a plan,", g: true}, {t: " not luck."}]]},
      {dur: 1, fontSize: 96, lines: [[{t: "We smooth the"}], [{t: "feast-or-famine"}], [{t: "into a salary."}]], allGreen: true},
      {dur: 1, fontSize: 98, lines: [[{t: "Pay yourself steady."}]], cta: CTA},
    ],
  },
  {
    id: "carousel-solo",
    title: "A Job, Not A Business",
    chip: "A Job, Not A Business",
    cover: {image: "solo.jpg", headline: [[{t: "You gave yourself"}], [{t: "a job, not"}], [{t: "a business."}]]},
    slides: [
      {dur: 1, fontSize: 94, lines: [[{t: "If it stops when"}], [{t: "you stop, it's"}], [{t: "a job.", g: true}]]},
      {dur: 1, fontSize: 94, lines: [[{t: "You never paid"}], [{t: "yourself a "}, {t: "real wage.", g: true}]]},
      {dur: 1, fontSize: 92, lines: [[{t: "No numbers means"}], [{t: "no way "}, {t: "to grow out.", g: true}]]},
      {dur: 1, fontSize: 96, lines: [[{t: "We build the numbers"}], [{t: "that make it"}], [{t: "a business."}]], allGreen: true},
      {dur: 1, fontSize: 100, lines: [[{t: "Build the business."}]], cta: CTA},
    ],
  },
  {
    id: "carousel-retail",
    title: "Where'd It Go",
    chip: "Where'd It Go?",
    cover: {image: "retail.jpg", headline: [[{t: "Great month."}], [{t: "Where'd it go?"}]]},
    slides: [
      {dur: 1, fontSize: 94, lines: [[{t: "Sales were up."}], [{t: "Cash "}, {t: "vanished", g: true}], [{t: "anyway."}]]},
      {dur: 1, fontSize: 92, lines: [[{t: "Inventory ate the"}], [{t: "profit and "}, {t: "sat", g: true}], [{t: "on a shelf.", g: true}]]},
      {dur: 1, fontSize: 94, lines: [[{t: "Cash tied up in"}], [{t: "stock "}, {t: "isn't cash.", g: true}]]},
      {dur: 1, fontSize: 98, lines: [[{t: "We track margin"}], [{t: "and inventory"}], [{t: "together."}]], allGreen: true},
      {dur: 1, fontSize: 102, lines: [[{t: "Find the money."}]], cta: CTA},
    ],
  },
  {
    id: "carousel-trades",
    title: "Bid In Your Head",
    chip: "You Bid It In Your Head",
    cover: {image: "trades.jpg", headline: [[{t: "Bid in your head."}], [{t: "Paid from"}], [{t: "your wallet."}]]},
    slides: [
      {dur: 1, fontSize: 94, lines: [[{t: "A number you didn't"}], [{t: "write down is"}], [{t: "a guess.", g: true}]]},
      {dur: 1, fontSize: 96, lines: [[{t: "You "}, {t: "ate", g: true}, {t: " the parts,"}], [{t: "the drive,"}], [{t: "and the redo."}]]},
      {dur: 1, fontSize: 94, lines: [[{t: "The margin was"}], [{t: "gone", g: true}, {t: " before"}], [{t: "you started."}]]},
      {dur: 1, fontSize: 98, lines: [[{t: "We build estimates"}], [{t: "off real cost,"}], [{t: "not memory."}]], allGreen: true},
      {dur: 1, fontSize: 100, lines: [[{t: "Quote from data."}]], cta: CTA},
    ],
  },
];
